### ISSUE TITLE
Add support for custom JsonSerializerSettings

### ISSUE THREAD

**Issue by reneherrero** [ElasticLINQ/ElasticLINQ#50]
Hi,

First off, GREAT WORK!!!

Being able to set the JsonSerializerSettings come time to deserialize a JObject in a Hit object would be great.

I found the place the settings need to go in the ElasticQueryTranslator class.  The JObject.ToObject method can receive a custom JSonSerializer.  Here’s the quick fix we put in place:

``` csharp
private Func<Hit, Object> DefaultItemProjector
{
  get
  {
    return hit => hit._source
      .SelectToken(Mapping.GetDocumentMappingPrefix(sourceType) ?? "")
      .ToObject(sourceType, Newtonsoft.Json.JsonSerializer.Create(new Dell.ComplexConfig.Formatting.V1.CcsSerializerSettings()));
  }
}
```

I’m guessing that passing the JsonSerializerSettings to the ElasticContext constructor and letting them trickle down would be the way to go.

Any way for us to contribute?

Thanks,

Rene

**Comment by damieng** [comment]
Hi.

This is something we could support, I'll take a look at possible entry points. Might be worth actually accepting a whole JsonSerializer rather than just the settings. Also need to consider the various places we do deserialization not just the default item projector.

Out of curiosity which settings are you changing?

**Comment by damieng** [comment]
You can now override the materialization in the mapping.
