### ISSUE TITLE
Connection Pooling

### ISSUE THREAD

**Issue by jonathanstowell** [ElasticLINQ/ElasticLINQ#76]
Hi,

We (FundsLibrary) have recently adopted ElasticLINQ as a technology to aid us in creation of a OData WebAPI project we have undertaken.

As part of that project we needed support for Connection Pooling. After looking at ElasticLINQ we decided the best way to do this would be to refactor it to take in a IElasticsearchClient and use Elasticsearch-net to issue requests to Elasticsearch.

We have carried out this work on a branch here: https://github.com/FundsLibrary/ElasticLINQ/tree/elasticsearch-net

I believe I saw on another Issue that you were considering re-factoring to use Elasticsearch-net at some point, but were too short on time to do so.

If you could take a look at the provided branch and perhaps provide feedback on what has been done so far / additional things you think need to be done, and whether you would consider accepting this as a pull request now or in the future after feedback.

It would be great to work with you guys on this, as this library has saved us a lot of time in using OData with Elasticsearch.

Thanks,

Jon

**Comment by damieng** [comment]
Hi Jon.  Had a quick look - one thing that is concerning me right now is that the HttpClient is totally removed so this change would force people to switch to Wlasticsearch.net whether they wanted to or not.

Might be nice to have the option in the short term.

Will take a look at the rest over the next few days.

**Comment by jonathanstowell** [comment]
Yes this would no doubt be a breaking change, although with this the consumers would be forced to have a dependency on elasticsearch-net if they did still only want to use the HttpClient which wouldn't be ideal either.

This was just an approach we were considering taking as we felt the elasticsearch-net client is great at what it does with its ability to allow the consumer to have intricate controller over the connection settings, and your library is great at converting LINQ expressions to Elasticsearch queries. However the functionality around the client sending the requests to elastic search is fairly basic.

We were wondering how you would go about adding support for connection pooling to ElasticLINQ? Do you think its best kept it separate from Elasticsearch-net? With people starting to add more complex options straight to ElasticLINQ, or would it be best to leverage Elasticsearch-net?

Also we assume that this is not just a project you've created out of curiosity, but one you've created to serve a purpose for a particular product? Are you working with a cluster of Elasticsearch nodes and if so how are you handling that?

Our concern at the moment is that by only having ElasticLINQ sending requests to one of our Elasticsearch nodes, if that node were to drop out, than the service dies with it instead of the client working out it can now only send requests to the second node.

**Comment by damieng** [comment]
This product is actually used in production for many thousands of requests daily across the world here at Centurylink Cloud.  We actually use HaProxy to front our Elasticsearch nodes so they are actively removed from the available pool without ElasticLINQ needing to do anything if they go bad. We realize that the rest of the world isn't doing that which is why we definitely want to leverage the stuff in Elasticsearch.Net. 

There are two issues we need to figure out:
1. If we take Elasticsearch.NET as-is today we can't be portable class library any more as their packages are .NET40 and .NET45 only. This is a problem for anyone wanting to use this library on a client platform.
2. Are there any other issues with switching over to Elasticsearch.Net - e.g. authentication, compression, timeouts etc. 

One option in the short term might be to open up a bit of ElasticLINQ to allow the connection management to be easily substituted and to provide a second ElasticLINQ-via-Elasticsearch.NET one that takes the dependency on Elasticsearch.NET and provides the alternative connection manager you can then wire up.

Thoughts?

**Comment by jonathanstowell** [comment]
Its funny you say that as we were discussing the exact same approach yesterday at work. Perhaps re-factoring the connection management so its behind an interface and allowing that dependency to be provided.

We thought we could keep the default HttpClient in the ElasticLinq framework as a default connection provider but then people could override it with their preference if desired. These adapters could probably come in the form of other nuget packages that can sit on top of ElasticLinq.

I'll have a play with this over the next week or so and see what I can come up with.

Thanks for your input on this.

**Comment by jonathanstowell** [comment]
Hi Damien,

Had a play today with creating an abstraction for the ElasticConnection to allow it be swapped out for something else. Ended up placing the logic to create the url / make the request on this object which also had the HttpClient on it:

https://github.com/FundsLibrary/ElasticLINQ/tree/connection-abstraction/Source

It would then become possible for others to implement IElasticConnection and provide their own implementation for the Search method as shown here:

https://github.com/FundsLibrary/ElasticLINQ.ElasticsearchNet/blob/master/ElasticLINQ.ElasticsearchNet/ElasticNetConnection.cs

This shouldn't be a breaking change, as the constructor for ElasticContext/ElasticConnection remains the same. Just ElasticContext now takes a IElasticConnection which ElasticConnection now implements.

**Comment by damieng** [comment]
This looks really good!

I'd recommend naming the Search method SearchAsync given it returns a task and reformatting the file with whitespace rather than tabs so it stays consistent.

Making IFacets public is a bit of a pain as they're to be replaced with Aggregates which is a big piece of work. I'll see if I can at least fix the name and make them generic enough to survive the transition.

**Comment by jonathanstowell** [comment]
Thanks, I've renamed the method and created a pull request. I hope branching from master and not dev was the correct thing to do?

I was reading about Facets yesterday and I believe at some point in the future we may require moving to using aggregates instead as I believe you can reduce the size of the document being returned by only selecting the parts you need? However I can't see us looking at this for a little while.

If you start that work, let me know and perhaps we can contribute and help you out.

**Comment by damieng** [comment]
Integrated, thanks!
